# Capstone Project

## Topic: The Factors of World Happiness

### 1. Introduction
#### Happiness is closely related to the quality of life and life satisfaction of people. As a citizen of Hong Kong, a city with the longest longevity in the world and good economy, it ranks low in liveability and happiness though. I found the relationships between are quite interesting, and therefore in this project, I would like to use metrics to investigate different factors and their importance to the happiness level. By identifying the significant factors through data analysis, countries and their governors can reflect on themselves for improvements, as well as to create a better environment for its residents to live a happy and quality life.

### 2. Data
#### There are two datasets used in this project. All the data sources are downloaded from Kaggle. 
#### 1) 2015 World Happiness Index

In [4]:
#Import happiness report data
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_e9f96d10605444448e805f3c23c44609 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='SfR52bCJDFY88aOlRp8PPEiVItwV4ZqAZ7P03fHp9VKE',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_e9f96d10605444448e805f3c23c44609.get_object(Bucket='courseracapstone-donotdelete-pr-helg0wnmao2fxf',Key='2015.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [5]:
df_data_1.shape

(158, 12)

#### 2) World Capitals GPS

In [3]:
body = client_e9f96d10605444448e805f3c23c44609.get_object(Bucket='courseracapstone-donotdelete-pr-helg0wnmao2fxf',Key='concap.csv')['Body']

#add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_2 = pd.read_csv(body)
df_data_2.head()

,CountryName,CapitalName,CapitalLatitude,CapitalLongitude,CountryCode,ContinentName
0,Somaliland,Hargeisa,9.550000,44.050000,NaN,Africa
1,South Georgia and South Sandwich Islands,King Edward Point,-54.283333,-36.500000,GS,Antarctica
2,French Southern and Antarctic Lands,Port-aux-Français,-49.350000,70.216667,TF,Antarctica
3,Palestine,Jerusalem,31.766667,35.233333,PS,Asia
4,Aland Islands,Mariehamn,60.116667,19.900000,AX,Europe

In [6]:
df_data_2.shape

(245, 6)